export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAILURE = 'ALL_USERS_FAILURE'

export const SINGLE_USERS_REQUEST = 'SINGLE_USERS_REQUEST'
export const SINGLE_USERS_SUCCESS = 'SINGLE_USERS_SUCCESS'
export const SINGLE_USERS_FAILURE = 'SINGLE_USERS_FAILURE'


export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'