export const TRANS_REQUEST_DATA=' TRANS_REQUEST_DATA'
export const TRANS_SUCCESS_DATA=' TRANS_SUCCESS_DATA'
export const TRANS_ERROR_DATA=' TRANS_ERROR_DATA'


export const TRANS_ALL_REQUEST_DATA=' TRANS_ALL_REQUEST_DATA'
export const TRANS_ALL_SUCCESS_DATA=' TRANS_ALL_SUCCESS_DATA'
export const TRANS_ALL_ERROR_DATA=' TRANS_ALL_ERROR_DATA'


export const TRANSFER_REQUEST_DATA=' TRANSFER_REQUEST_DATA'
export const TRANSFER_SUCCESS_DATA=' TRANSFER_SUCCESS_DATA'
export const TRANSFER_ERROR_DATA=' TRANSFER_ERROR_DATA'